/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/index" |
       "/pages/admin/admins" |
       "/pages/admin/companies" |
       "/pages/admin/idVerify" |
       "/pages/admin/index" |
       "/pages/admin/jobs" |
       "/pages/admin/system" |
       "/pages/admin/users" |
       "/pages/message/chatList" |
       "/pages/message/chatRoom" |
       "/pages/message/index" |
       "/pages/mine/about" |
       "/pages/mine/certificate" |
       "/pages/mine/changePhone" |
       "/pages/mine/credit" |
       "/pages/mine/feedback" |
       "/pages/mine/index" |
       "/pages/mine/interview" |
       "/pages/mine/jobCollection" |
       "/pages/mine/referralHistory" |
       "/pages/mine/setting" |
       "/pages/mine/submitted" |
       "/pages/mine/verification" |
       "/pages/recommendation/index" |
       "/pages/recommendation/insert" |
       "/pages/recruiter/index" |
       "/pages/recruiter/jobPosting" |
       "/pages/recruiter/myJobs" |
       "/pages/recruiter/newsDetail" |
       "/pages/recruiter/registration" |
       "/pages/recruiter/reset" |
       "/pages/recruiter/resumeCenter" |
       "/pages/recruiter/resumeDetail" |
       "/pages/recruiter/talents" |
       "/pages/recruiter/verificationPhone" |
       "/pages/seeker/index" |
       "/pages/recommendation/detail/company" |
       "/pages/recommendation/detail/index" |
       "/pages/recommendation/position/index" |
       "/pages/recruiter/aiJobPosting/index" |
       "/pages/seeker/resumeCenter/Information" |
       "/pages/seeker/resumeCenter/education" |
       "/pages/seeker/resumeCenter/index" |
       "/pages/seeker/resumeCenter/job" |
       "/pages/seeker/resumeCenter/project" |
       "/pages/seeker/resumeCenter/selfDesc" |
       "/pages/seeker/tailorResume/detail" |
       "/pages/seeker/tailorResume/index" |
       "/pages/seeker/resumeCenter/workCertification/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
